apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: cloud-resource-config
      namespace: ${INSTALLATION_NAMESPACE}
    data:
      managed: >
        {"blobstorage":"aws", "smtpcredentials":"aws", "redis":"aws", "postgres":"aws"}
      workshop: >
        {"blobstorage":"openshift", "smtpcredentials":"openshift", "redis":"openshift", "postgres":"openshift"}
parameters:
  - name: INSTALLATION_NAMESPACE
    required: true